### ISSUE TITLE
Please update jaxb dependency to 3.0.0

### ISSUE THREAD

**Issue by robseidel** [FasterXML/jackson-modules-base#128]
version.jaxb.impl in jackson-modules-base/jaxb/pom.xml points to version 2.3.3 and not to the newest version (3.0.0).

The old implementation use some package names it shouldn't, causing conflicts with other dependencies.

**Comment by cowtowncoder** [comment]
TL;DNR; I think #116 does what you want.

@robseidel is that the version that completely changes API implemented (javax->jakarta), and in general will break every existing dependency if it was changed?
(part of big breaking "j2ee to jakarta" upgrade Oracle is hoping to complete, talked about here https://blogs.oracle.com/javamagazine/transition-from-java-ee-to-jakarta-ee for example)

If so, simply changing the dependency would absolutely not work: it would likely break all existing users. However, there is a possible solution via #116 in which alternative jar has been published since 2.12.0, with classifier "jakarta", and which has been post-processed to implement the new API (despite conceptually being replacement, jakarta APIs are not related in any way as far as Maven can see: different packages means different classes for class loader).

**Comment by robseidel** [comment]
Problem is, that 2.3 introduced breaking changes to the old packages and classes, which shouldn't have been done in the first place. It was corrected by changing the package with 3.0. 
So it would be better to depend on either 2.2 or >3.0, not on the broken 2.3.
And the class loader is exactly the problem I run into, when using jackson-module-jaxb-annotations > 2.9.8. Cause the changed classes result in conflicts, because other artifacts include the old sun classes too, like metro (glassfish).

I'll take a look at the merge requests, but it would probably not fix my problem, because the root cause is this bad dependency.

**Comment by cowtowncoder** [comment]
@robseidel Can you elaborate on breakage wrt 2.3? I am not familiar with issues here so I can't really comment on that without understanding what kind of breakage you are talking about
(my initial guess wrt jaxb/jakarta difference was incorrect)

I am especially puzzled by 2.3.2 dependency being problematic since that has been the dependency for quite a long time here and isn't something that changed lately? (nor reported by others)

**Comment by robseidel** [comment]
https://github.com/eclipse-ee4j/jaxb-api/commit/e7b5f04dcb93c2269b34699d4b7ef08ee6f5c7ae

This is the only breaking change I can find. But the metro version, I use (webservices-api:2.4.3) includes this change too. So it cannot cause conflicts. I can't specify why I got problem in the past with this.

Metro is now also released in version 3.0.0, so I will move on to use the the new jakarta packages in the future, so the artifacts cannot interfere.

Sorry for the trouble. I think this can be closed.

**Comment by cowtowncoder** [comment]
Ok. Let me know if there are further issues; the whole jakarta/javax situation is a bit problematic from my perspective (esp. on OSGi side it seems).

On dependency, please note that you can also override jaxb api dependency that this module indicates.
