### ISSUE TITLE
XmlAnyElement not mapped

### ISSUE THREAD

**Issue by Manfred73** [FasterXML/jackson-modules-base#158]
I generated some java classes with the jaxb2-maven-plugin based on an xsd that was provided to me. I used jakarta libraries in the plugin to generate the classes with the jakarta packages instead of the older javax packages.

I now have a Rest controller which receives and xml and I want to convert the xml to the generated someMessage model, e.g.:

```
@PostMapping(consumes = { MediaType.APPLICATION_XML_VALUE })
@Transactional
public ResponseEntity<?> post(@RequestBody SomeMessage someMessage) {
	// do something with someMessage
	return ResponseEntity.ok().build();
}
```

I read somewhere that you could register the following bean in Spring like so:

```
@Bean
public com.fasterxml.jackson.databind.Module jaxbModule() {
	return new JakartaXmlBindAnnotationModule();
}
```

For the most part this seems to work, except for the XmlAnyElement. The any element in the message remains null and is not mapped correctly.
Is this not yet supported (like mentioned here: http://fasterxml.github.io/jackson-module-jaxb-annotations/javadoc/2.5/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.html)
(XmlAnyElement not yet used, may be as per [JACKSON-253]).

I can't seem to find [JACKSON-253].

**Comment by cowtowncoder** [comment]
`XmlAnyElement` is not supported and likely never will be. The problem is that it essentially says "bind contents as XML-specific type (JAXBElement)" which is not something that would work well with Jackson: neither applicable to non-XML content, nor using types Jackson should support -- Jackson is not (nor tries to be or will be) JAXB (or, Jakarta-binding) implementation, not even XML module: there is support for using JAXB annotations best it can. And this is one of annotations that cannot be meaningfully supported.

Reference to [JACKSON-253] is obsolete as that relates to Jackson 1.x bug tracker at Codehaus which shut down by 2016. I'll change javadocs to remove that reference.

**Comment by Manfred73** [comment]
Thanks for the feedback.
Then we'll go for Jaxb unmarshaller and some messageconverter.
