### ISSUE TITLE
[mrbean] Failed to load class com.fasterxml.jackson.module.mrbean.generated...

### ISSUE THREAD

**Issue by mancvso** [FasterXML/jackson-modules-base#5]
I'm using the Play! framework in Java with an interface like

```java
public interface AbstractMsg {
	public String getValue();
}
```

And registered mapper modules at startup
```java
ObjectMapper mapper = play.libs.Json.mapper();
mapper.registerModule(new ParameterNamesModule());
mapper.registerModule(new MrBeanModule());
play.libs.Json.setObjectMapper(mapper);
```

And when trying to "materialize" the interface with JSON content
```json
{ "value" : "did it work?" }
```

I get a nice Exception
```
akka.actor.OneForOneStrategy - com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.fasterxml.jackson.module.mrbean.generated.models.mensajes.AbstractMsg': models/mensajes/AbstractMsg
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.fasterxml.jackson.module.mrbean.generated.models.mensajes.AbstractMsg': models/mensajes/AbstractMsg
...
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.fasterxml.jackson.module.mrbean.generated.models.mensajes.AbstractMsg': models/mensajes/AbstractMsg
```

I have to mention that the "materialization" on the interface is happening inside an Actor, which can run in a different thread from which the ObjectMapper and this module was instantiated.

I have tried different combinations and could not find the cause, but I suspect the class loader of the framework is not available to Jackson, but I'm only speculating.

Java: 1.8
Play: 2.4, 2.5
Module version 2.6.0, 2.6.1, 2.7.1

**Comment by cowtowncoder** [comment]
I really would need a reproduction here to know for sure... but I am guessing that perhaps there is some polymorphic type handling, including class name of materialized type (class generated by MrBean), being sent to something else that does NOT have access to the original type. Such type is and can not be made available, as mr bean can only create and load class within local JVM.

**Comment by mancvso** [comment]
Well, I do only use one JVM, that's sure. I've run without a forked JVM and it's still not working for me.
With a reproduction you mean a complete Play! application? A Dockerfile maybe?

**Comment by cowtowncoder** [comment]
@mancvso with reproduction I mean a stand-alone test case that does not rely on external frameworks. Cut'n paste of single unit test class works; a github project; gist, whatever. But a play application (or dropwizard, spring boot, swagger etc) can be more problematic in that there are things that are not easy to control. Ultimately I would also like to include simplified reproduction as regression test, and that's where other frameworks are problematic.

**Comment by jroper** [comment]
For reference, the problem here was that Play has a classloader hierarchy where all static classes (ie, library jars) are in a parent classloader, while all application classes are in a child of that - this is how we implement hot reloading, we just throw away the applications classes, rather than needing to throw away every library, which would be too expensive to effectively implement the reloader.  By default, the Jackson mr bean module uses the same classloader that it was loaded in, which means it can't see any of the application classes. The solution is straight forward, pass in an abstract type resolver that's been instantiated with the applications classloader.  See [this comment](https://github.com/playframework/playframework/issues/5617#issuecomment-182677942) for more details.

**Comment by cowtowncoder** [comment]
@jroper Makes sense -- thank you for documenting the solution needed. I assume there isn't much module (or Jackson) can do to figure out `ClassLoader`, although if there are improvements I am always open to improvements.

**Comment by jroper** [comment]
Generally, the context classloader is a better default, Play always sets the context classloader during initialisation so it should pick it up with no problems.  Though the most important thing is to always provide a mechanism for explicitly providing the classloader, since in many contexts, the context classloader is completely unspecified.  The mr bean module obviously does provide a mechanism to explicitly provide a classloader, so it's fine.
