### ISSUE TITLE
Jackson internal dependency for 'jackson-annotations' not in sync.

### ISSUE THREAD

**Issue by skjolber** [FasterXML/jackson-modules-base#66]
Has Jackson-annotations intentionally been left on version 2.9.0 in the later releases? The Jackson 'release train' otherwise seems to update all artifacts to the same version, i.e. keep stuff 'in sync'. 

See for example 'Compile Dependencies' under https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.9.7

**Comment by cowtowncoder** [comment]
Yes, that is intentional.

All annotations patch versions should be functionally identical. With 3.x we will drop the patch number completely, but it was kept originally in 2.x as some users expressed preference for using just a single value. But since introduction of `jackson-bom` that specifies consistent set of versions, and can be relied on with just a single version number itself, this will not be needed.
