### ISSUE TITLE
Migrate JAXB module to Jakarta EE 9

### ISSUE THREAD

**Issue by tamersaadeh** [FasterXML/jackson-modules-base#96]
Jakarta EE 9 platform renames all the "old" namespaces from javax.* to jakarta.*. This pull request performs this migration so that when Jacakrta EE 9 is released in [June 2020](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan#proposed-progress-reviews) it will be compatible. Initial PR in #95.

**Comment by darmbrust** [comment]
Any idea when a beta version may be built that supports this?  Been trying to test some of the other project that do have alpha support for the change... but lots of chicken-or-the-egg problems in getting an entire env up and running.

**Comment by cowtowncoder** [comment]
@darmbrust have a look at PR itself, #95 -- not sure if and when this could proceed. Probably not for 2.12, it seems?

**Comment by chris21k** [comment]
As far as I can see, all related artifacts are finally converted / released with the new jakarta namespace. Please convert also jackson-module-jaxb-annotation .

Thanks,
Chris

**Comment by cowtowncoder** [comment]
@chris21k Yes, I think JAX-RS modules are dual-published now to allow choice of old/new jax-ws package.
But same is true for `jackson-module-jaxb-annotations` too:

https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.12.0/

so that with classifier of `jakarta` you can select dependency to Jakarta APIs.

**Comment by chris21k** [comment]
@cowtowncoder Many thanks for the hint: using jackson-module-jaxb-annotations-2.12.0-jakarta.jar instead of jackson-module-jaxb-annotations-2.12.0.jar works. 

I have overlooked the existence of that file, sorry fir that. However, I am somehow surprised, that there are two different jars, as there are'nt two different jars neither for jackson 2.12.0 core under https://repo1.maven.org/maven2/com/fasterxml/jackson/core/ nor for (some/all?) other modules under https://repo1.maven.org/maven2/com/fasterxml/jackson/module/ . These libraries seem to use only the new name space in their new version 2.12 . Probably, I was misled further since this bug entry is still open.

**Comment by cowtowncoder** [comment]
@chris21k I am not sure why there should be multiple jars of `jackson-core` which has no external dependencies?

Only modules that rely on JAX-xxx dependencies require this workaround: JAXB annotations module, and JAX-RS provider modules; and they in turn are not depended on by other Jackson modules -- with one minor exception (jackson-dataformat-xml does have dependency to jaxb annotations module).

This bug entry is open, for now, since it is possible that at some point we might want to convert this module to only rely on Jakarta versions. Or perhaps it should be closed -- the whole issue is quite new, and the situation with Jakarta packages looks like classic FUBAR problem for short term at least, so ... we'll see. :)

**Comment by cowtowncoder** [comment]
Solved for 2.13 by #130: separate module now
